[[redirects]]
    from = "/divjoy-how-to-start-a-side-project-in-less-than-2-hrs"
    to = "/divjoy-is-it-worth-it"
    force = true

[[redirects]]
    from = "/Divjoy-How-to-start-a-side-project-in-less-than-2-hrs"
    to = "/divjoy-is-it-worth-it"
    force = true

[[redirects]]
    from = "https://developerspin.com"
    to = "https://drew.tech"
    force = true

[[redirects]]
    from = "https://developerspin.com/*"
    to = "https://drew.tech/:splat"
    force = true