[[redirects]]
    from = "https://developerspin.com/posts/2020-01-05-how-to-create-cron-job-now-zeit/"
    to = "https://developerspin.com/how-to-create-cron-job-now-zeit/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-11-27-on-turning-off-notifications/"
    to = "https://developerspin.com/on-turning-off-notifications/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-11-20-functionality-not-enabled/"
    to = "https://developerspin.com/functionality-not-enabled/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-10-15-A-5-step-framework-for-picking-tech/"
    to = "https://developerspin.com/A-5-step-framework-for-picking-tech/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-06-how-to-get-rich-notes/"
    to = "https://developerspin.com/how-to-get-rich-notes/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-10-01-podcast-day/"
    to = "https://developerspin.com/podcast-day/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-17-building-great-software-with-google-analytics/"
    to = "https://developerspin.com/building-great-software-with-google-analytics/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-15-moving-domains-on-netlify/"
    to = "https://developerspin.com/moving-domains-on-netlify/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-16-why-I-didnt-tell-you/"
    to = "https://developerspin.com/why-I-didnt-tell-you/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-27-should-i-buy-this-house/"
    to = "https://developerspin.com/should-i-buy-this-house/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-05-sideproject-tech/"
    to = "https://developerspin.com/sideproject-tech/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-05-29-I-moved-to-netlify/"
    to = "https://developerspin.com/I-moved-to-netlify/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-01-03-sharing-podcasts/"
    to = "https://developerspin.com/sharing-podcasts/"
    force = true

[[redirects]]
    from = "https://developerspin.com/about/"
    to = "https://developerspin.com/authors/Drew-Bredvick/"
    force = true

[[redirects]]
    from = "https://developerspin.com/contact/"
    to = "https://developerspin.com/authors/Drew-Bredvick/"
    force = true