[[redirects]]
    from = "https://developerspin.com/posts/2020-01-05-how-to-create-cron-job-now-zeit/"
    to = "https://developerspin.com/How-to-Create-a-Cron-Job-with-NextJS-and-Now/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-11-27-on-turning-off-notifications/"
    to = "https://developerspin.com/On-Turning-Off-Notifications/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-11-20-functionality-not-enabled/"
    to = "https://developerspin.com/How-to-Send-Email-with-Zeit.co-Domain-through-GSuite/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-10-15-A-5-step-framework-for-picking-tech/"
    to = "https://developerspin.com/Starting-a-Startup:-A-5-Step-Framework-for-Picking-Tech/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-15-moving-domains-on-netlify/"
    to = "https://developerspin.com/How-to-Change-Domains-on-Netlify/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-06-how-to-get-rich-notes/"
    to = "https://developerspin.com/How-to-Get-Rich-(Naval)-Notes/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-10-01-podcast-day/"
    to = "https://developerspin.com/My-September-Podcast-Stack/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-17-building-great-software-with-google-analytics/"
    to = "https://developerspin.com/A-Developer's-Guide-Building-Great-Software-Incrementally-with-Analytics/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-09-15-moving-domains-on-netlify/"
    to = "https://developerspin.com/moving-domains-on-netlify/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-16-why-I-didnt-tell-you/"
    to = "https://developerspin.com/Why-I-Didn't-Tell-You-That-I-Have-Cancer/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-27-should-i-buy-this-house/"
    to = "https://developerspin.com/Should-I-Buy-This-House/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-07-05-sideproject-tech/"
    to = "https://developerspin.com/Tech-decisions-and-developer-guilt/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-05-29-I-moved-to-netlify/"
    to = "https://developerspin.com/I-Moved-to-Netlify/"
    force = true

[[redirects]]
    from = "https://developerspin.com/posts/2019-01-03-sharing-podcasts/"
    to = "https://developerspin.com/Sharing-is-Caring/"
    force = true

[[redirects]]
    from = "https://developerspin.com/about/"
    to = "https://developerspin.com/authors/Drew-Bredvick/"
    force = true

[[redirects]]
    from = "https://developerspin.com/contact/"
    to = "https://developerspin.com/authors/Drew-Bredvick/"
    force = true

[[redirects]]
    from = "https://developerspin.com/How-to-Create-a-Cron-Job-with-NextJS-and-Now"
    to = "https://developerspin.com/One-percent-better-every-day-with-cron-jobs"
    force = true

[[redirects]]
    from = "https://developerspin.com/Building-your-own-blog-in-2020"
    to = "https://developerspin.com/My-principles-for-blogging"
    force = true

[[redirects]]
    from = "https://developerspin.com/How-to-Get-Rich-(Naval)-Notes"
    to = "https://developerspin.com/Notes-on-Naval's-Money"
    force = true

[[redirects]]
    from = "https://developerspin.com/Starting-a-Startup:-A-5-Step-Framework-for-Picking-Tech"
    to = "https://developerspin.com/How-I-pick-my-tech-stack-for-side-projects"
    force = true

[[redirects]]
    from = "https://developerspin.com/On-Turning-Off-Notifications"
    to = "https://developerspin.com/On-Turning-Off-Notifications"
    force = true